/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UnlockRouteImport } from './routes/unlock'
import { Route as ProfilesProfileIdRouteImport } from './routes/profiles.$profileId'
import { Route as RTokenRouteImport } from './routes/r.$token'
import { Route as AuditsIdIndexRouteImport } from './routes/audits.$id.index'
import { Route as AuditsIdReportRouteImport } from './routes/audits.$id.report'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UnlockRoute = UnlockRouteImport.update({
  id: '/unlock',
  path: '/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilesProfileIdRoute = ProfilesProfileIdRouteImport.update({
  id: '/profiles/$profileId',
  path: '/profiles/$profileId',
  getParentRoute: () => rootRouteImport,
} as any)
const RTokenRoute = RTokenRouteImport.update({
  id: '/r/$token',
  path: '/r/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditsIdIndexRoute = AuditsIdIndexRouteImport.update({
  id: '/audits/$id/',
  path: '/audits/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditsIdReportRoute = AuditsIdReportRouteImport.update({
  id: '/audits/$id/report',
  path: '/audits/$id/report',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/unlock': typeof UnlockRoute
  '/profiles/$profileId': typeof ProfilesProfileIdRoute
  '/r/$token': typeof RTokenRoute
  '/audits/$id/report': typeof AuditsIdReportRoute
  '/audits/$id/': typeof AuditsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/unlock': typeof UnlockRoute
  '/profiles/$profileId': typeof ProfilesProfileIdRoute
  '/r/$token': typeof RTokenRoute
  '/audits/$id/report': typeof AuditsIdReportRoute
  '/audits/$id': typeof AuditsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/unlock': typeof UnlockRoute
  '/profiles/$profileId': typeof ProfilesProfileIdRoute
  '/r/$token': typeof RTokenRoute
  '/audits/$id/report': typeof AuditsIdReportRoute
  '/audits/$id/': typeof AuditsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/unlock'
    | '/profiles/$profileId'
    | '/r/$token'
    | '/audits/$id/report'
    | '/audits/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/unlock'
    | '/profiles/$profileId'
    | '/r/$token'
    | '/audits/$id/report'
    | '/audits/$id'
  id:
    | '__root__'
    | '/'
    | '/unlock'
    | '/profiles/$profileId'
    | '/r/$token'
    | '/audits/$id/report'
    | '/audits/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UnlockRoute: typeof UnlockRoute
  ProfilesProfileIdRoute: typeof ProfilesProfileIdRoute
  RTokenRoute: typeof RTokenRoute
  AuditsIdReportRoute: typeof AuditsIdReportRoute
  AuditsIdIndexRoute: typeof AuditsIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unlock': {
      id: '/unlock'
      path: '/unlock'
      fullPath: '/unlock'
      preLoaderRoute: typeof UnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiles/$profileId': {
      id: '/profiles/$profileId'
      path: '/profiles/$profileId'
      fullPath: '/profiles/$profileId'
      preLoaderRoute: typeof ProfilesProfileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$token': {
      id: '/r/$token'
      path: '/r/$token'
      fullPath: '/r/$token'
      preLoaderRoute: typeof RTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audits/$id/': {
      id: '/audits/$id/'
      path: '/audits/$id'
      fullPath: '/audits/$id/'
      preLoaderRoute: typeof AuditsIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audits/$id/report': {
      id: '/audits/$id/report'
      path: '/audits/$id/report'
      fullPath: '/audits/$id/report'
      preLoaderRoute: typeof AuditsIdReportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UnlockRoute: UnlockRoute,
  ProfilesProfileIdRoute: ProfilesProfileIdRoute,
  RTokenRoute: RTokenRoute,
  AuditsIdReportRoute: AuditsIdReportRoute,
  AuditsIdIndexRoute: AuditsIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
